#!/bin/bash
cd "$(dirname "$0")"
source .env

if [ $# -eq 0 ]; then
	echo "No arguments provided"
	exit 1
fi

if [ ! -z "$USE_CUSTOM_APACHE_USER" ]
then
    USER_COMMAND="--user $USE_CUSTOM_APACHE_USER "
else
    USER_COMMAND=""
fi

case $1 in
    start)
        docker-compose up -d
        ;;
    start8)
        docker-compose -f docker-compose-8.yml up -d
        ;;
    start81)
        docker-compose -f docker-compose-81.yml up -d
        ;;
    stop)
        docker-compose down
        ;;
    sh)
        docker exec -it $USER_COMMAND newspack_dev /bin/bash
        ;;
    rsh)
        docker exec -it newspack_dev /bin/bash
        ;;
    shell)
        docker exec -it $USER_COMMAND newspack_dev sh -c "wp shell --allow-root"
        ;;
    wp)
        cmd="wp --allow-root ${@:2}"
        docker exec -it $USER_COMMAND newspack_dev $cmd
        ;;
    install)
        docker exec -it $USER_COMMAND newspack_dev sh -c "/var/scripts/install.sh"
        ;;
    uninstall)
        docker exec -it $USER_COMMAND newspack_dev sh -c "/var/scripts/uninstall.sh"
        ;;
    build)
        docker exec -it $USER_COMMAND newspack_dev sh -c "/var/scripts/build-repos.sh $2"
        ;;
    watch)
        docker exec -it $USER_COMMAND newspack_dev sh -c "/var/scripts/watch-repo.sh $2"
        ;;
    test-php)
        docker exec -it $USER_COMMAND newspack_dev sh -c "/var/scripts/test-php.sh $2 ${@:3}"
        ;;
    test-js)
        docker exec -it $USER_COMMAND newspack_dev sh -c "/var/scripts/test-js.sh $2"
        ;;
    composer)
        docker exec -it $USER_COMMAND newspack_dev sh -c "/var/scripts/composer.sh $2 ${@:3}"
        ;;
    db)
        docker exec -it $USER_COMMAND newspack_dev sh -c "wp db cli --allow-root"
        ;;
    tail)
        tail -f html/wp-content/debug.log
        ;;
    secrets)
        docker exec -it $USER_COMMAND newspack_dev sh -c "wp eval-file /var/scripts/generate-secrets.php --allow-root"
        ;;
    jncp)
        cmd="/var/scripts/jn-cp.sh ${@:2}"
        docker exec -it $USER_COMMAND newspack_dev $cmd
        ;;
    jninit)
        cmd="/var/scripts/jn-init.sh ${@:2}"
        docker exec -it $USER_COMMAND newspack_dev $cmd
        ;;
    *)
        echo Unknown command
        ;;
esac

