version: 2.1

commands:
  e2e:
    steps:
      - checkout
      - attach_workspace:
          at: ~/
      - run:
          name: Hello
          command: echo "Hello, CI!"

executors:
  docker-playwright:
    docker:
      - image: mcr.microsoft.com/playwright:v1.42.0-jammy

jobs:
  stable:
    executor: docker-playwright
    steps:
      - e2e

workflows:
  version: 2
  test-stable:
    jobs:
      - stable
