version: 2.1

commands:
  e2e:
    steps:
      - checkout
      - attach_workspace:
          at: ~/
      - run:
          name: Create .env file from env vars
          command: printenv >> ./e2e/.env
      - run:
          name: Reset the test site
          command: |
            echo "Resetting the test site"
            apt-get update
            apt-get install sshpass
            mkdir -p /root/.ssh
            echo "$SSH_KNOWN_HOST" > /root/.ssh/known_hosts
            sshpass -p "$SSH_USER_PASS" scp ./bin/e2e-plugin.php $SSH_USER@$SSH_HOST:/htdocs/wp-content/plugins/
            sshpass -p "$SSH_USER_PASS" ssh -v $SSH_USER@$SSH_HOST 'bash -s' < ./bin/e2e-reset.sh
      - run:
          name: Run tests
          command: |
            cd e2e
            npm install
            npx playwright install chromium
            npm run test
      - store_artifacts:
          path: e2e/playwright-report
      - store_artifacts:
          path: e2e/test-results
      - run:
          name: Deploy to GitHub Pages
          command: |
            git config user.name "$GIT_COMMITTER_NAME"
            git config user.email "$GITHUB_COMMITER_EMAIL"
            git checkout -b gh-pages
            mv e2e/playwright-report docs
            cd docs
            git add --all
            git commit -m "Deploy Playwright Report [skip ci]"
            git push "https://${GITHUB_TOKEN}@github.com/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}.git" --force

executors:
  docker-playwright:
    docker:
      - image: mcr.microsoft.com/playwright:v1.42.0-jammy

jobs:
  stable:
    executor: docker-playwright
    steps:
      - e2e

workflows:
  version: 2
  test-stable:
    jobs:
      - stable
